language:
  python
python:
  '3.6'
sudo:
  true
before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install --no-install-recommends lame python3 locales opus-tools
  - locale-gen ru_RU.UTF-8
  - sudo apt-get -y install --no-install-recommends scons build-essential python3-pip
install:
  - pip install --upgrade pip setuptools wheel
  - pip install flask aiohttp pymorphy2 rhvoice-wrapper rhvoice-wrapper-bin
before_script:
  - git clone https://github.com/vantu5z/RHVoice-dictionary.git
  - sudo mkdir -p /usr/local/etc/RHVoice/dicts/Russian/
  - sudo cp RHVoice-dictionary/*.txt /usr/local/etc/RHVoice/dicts/Russian/
  - cp -R RHVoice-dictionary/tools .
  - export LD_LIBRARY_PATH=$(pip show rhvoice-wrapper-bin | grep Location | awk '{print $2}')/rhvoice_wrapper_bin/lib/
  - python app.py &
  - sleep 5
script:
  - python -u example/threaded_test.py
