language:
  python

python:
  '3.6'

services:
  - docker

sudo:
  required

git:
  depth: 1

before_install:
  - pip install aiohttp
  - docker build -t aculeasis/rhvoice-rest-test:arm64v8 -f Dockerfile.arm64v8 .
  - docker run -d -p 8080:8080 --name rhvoice-rest aculeasis/rhvoice-rest-test:arm64v8 -e THREADED=6
  - docker ps -a
  - sleep 5

script:
  - python -u example/threaded_test.py

after_script:
  - docker stop rhvoice-rest
  - docker ps -a
