language:
  python

matrix:
  include:
  - python: '3.6'
  - python: '3.6'
    env: RHVOICE_FCACHE=true
  - python: '3.6'
    env: CHUNKED_TRANSFER=true

services:
  - docker

sudo:
  required

git:
  depth: 1

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker --version
  - docker build -t aculeasis/rhvoice-rest-test:amd64 -f Dockerfile.amd64 .
  - docker run -d -p 8080:8080 -e RHVOICE_FCACHE_LIFETIME=12 -e THREADED=4 -e RHVOICE_FCACHE -e CHUNKED_TRANSFER --name rhvoice-rest aculeasis/rhvoice-rest-test:amd64
  - sleep 5
  - docker images
  - docker ps -a

install:
  - pip install aiohttp

script:
  - python -u example/threaded_test.py

after_script:
  - docker stop rhvoice-rest
  - docker logs rhvoice-rest
  - docker ps -a
