language:
  python
python:
  '3.6'
sudo:
  true
before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install --no-install-recommends libao4 libasound2 libportaudio2 lame python3 python3-pip python3-setuptools locales opus-tools
  - locale-gen ru_RU.UTF-8
  - sudo apt-get -y install --no-install-recommends scons build-essential libao-dev pkg-config flite1-dev portaudio19-dev
install:
  - pip install --upgrade pip setuptools wheel
  - pip install aiohttp pymorphy2 rhvoice-wrapper
before_script:
  - git clone https://github.com/Olga-Yakovleva/RHVoice.git
  - cd RHVoice
  - git checkout dc36179
  - scons
  - sudo scons install
  - sudo ldconfig
  - cd ..
  - git clone https://github.com/vantu5z/RHVoice-dictionary.git
  - sudo mkdir -p /usr/local/etc/RHVoice/dicts/Russian/
  - sudo cp RHVoice-dictionary/*.txt /usr/local/etc/RHVoice/dicts/Russian/
  - cp -R RHVoice-dictionary/tools .
  - python app.py &
  - sleep 5
script:
  - python -u example/threaded_test.py
